[debug] [2018-10-19T19:29:56.191Z] ----------------------------------------------------------------------
[debug] [2018-10-19T19:29:56.193Z] Command:       /usr/local/bin/node /usr/local/bin/firebase functions:shell
[debug] [2018-10-19T19:29:56.193Z] CLI Version:   5.0.1
[debug] [2018-10-19T19:29:56.193Z] Platform:      darwin
[debug] [2018-10-19T19:29:56.193Z] Node Version:  v10.4.1
[debug] [2018-10-19T19:29:56.194Z] Time:          Fri Oct 19 2018 16:29:56 GMT-0300 (GMT-03:00)
[debug] [2018-10-19T19:29:56.195Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-10-19T19:29:56.204Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-10-19T19:29:56.205Z] > authorizing via signed-in user
[debug] [2018-10-19T19:29:56.205Z] [iam] checking project dctb-mario-plan for permissions ["firebase.projects.get"]
[debug] [2018-10-19T19:29:56.207Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/dctb-mario-plan:testIamPermissions  

[debug] [2018-10-19T19:29:57.331Z] <<< HTTP RESPONSE 200
[debug] [2018-10-19T19:29:58.249Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:874:3)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Command.module.exports [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/functionsShellCommandAction.js:18:6)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:202:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2018-10-19T19:30:16.915Z] ----------------------------------------------------------------------
[debug] [2018-10-19T19:30:16.917Z] Command:       /usr/local/bin/node /usr/local/bin/firebase functions:shell
[debug] [2018-10-19T19:30:16.917Z] CLI Version:   5.0.1
[debug] [2018-10-19T19:30:16.917Z] Platform:      darwin
[debug] [2018-10-19T19:30:16.917Z] Node Version:  v10.4.1
[debug] [2018-10-19T19:30:16.918Z] Time:          Fri Oct 19 2018 16:30:16 GMT-0300 (GMT-03:00)
[debug] [2018-10-19T19:30:16.918Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-10-19T19:30:16.928Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-10-19T19:30:16.928Z] > authorizing via signed-in user
[debug] [2018-10-19T19:30:16.929Z] [iam] checking project dctb-mario-plan for permissions ["firebase.projects.get"]
[debug] [2018-10-19T19:30:16.930Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/dctb-mario-plan:testIamPermissions  

[debug] [2018-10-19T19:30:17.975Z] <<< HTTP RESPONSE 200
[debug] [2018-10-19T19:30:18.456Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:874:3)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Command.module.exports [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/functionsShellCommandAction.js:18:6)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:202:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2018-10-19T19:30:37.057Z] ----------------------------------------------------------------------
[debug] [2018-10-19T19:30:37.059Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions
[debug] [2018-10-19T19:30:37.059Z] CLI Version:   5.0.1
[debug] [2018-10-19T19:30:37.059Z] Platform:      darwin
[debug] [2018-10-19T19:30:37.059Z] Node Version:  v10.4.1
[debug] [2018-10-19T19:30:37.060Z] Time:          Fri Oct 19 2018 16:30:37 GMT-0300 (GMT-03:00)
[debug] [2018-10-19T19:30:37.060Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-10-19T19:30:37.069Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-10-19T19:30:37.069Z] > authorizing via signed-in user
[debug] [2018-10-19T19:30:37.070Z] [iam] checking project dctb-mario-plan for permissions ["firebase.projects.get"]
[debug] [2018-10-19T19:30:37.072Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/dctb-mario-plan:testIamPermissions  

[debug] [2018-10-19T19:30:37.384Z] <<< HTTP RESPONSE 200
[debug] [2018-10-19T19:30:37.386Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/dctb-mario-plan  
 
[debug] [2018-10-19T19:30:38.326Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Applications/XAMPP/xamppfiles/htdocs/dctb-ninja-react-redux-firebase'...
[info] 
[debug] [2018-10-19T19:30:38.782Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:874:3)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:47:12)
[error] 
[error] Error: An unexpected error has occurred.
